### ISSUE TITLE
Create Top of Book graph component

### ISSUE THREAD

**Issue by panoreak** [Lercerss/graphelier#108]
Create a graph that shows the value of the best bid and best ask of the order book for an entire day (graph functionality will be extended in future tasks).

# Tasks
- [x] Make mockup
- [x] Find a suitable graph library that will allow zooming/panning
- [x] Create a graph component that shows best bid/ask price over time for the selected day
- [x] Load graph for selected day when a day is picked. Set selected time to 9:30 am by default
        -Make request using route from issue #111
        -Use data to populate graph
- [x] Reload order book when a time is clicked on the graph, put marker at that time (keep marker at selected time)

Story: [#86]
Pull request: [#160]

**Comment by panoreak** [comment]
Quick Mockup of best asks/bids over time:
![image](https://user-images.githubusercontent.com/25068506/69189263-0e7f3a00-0aec-11ea-9dc3-4ddeb4d174a3.png)

**Comment by panoreak** [comment]
> Quick Mockup of best asks/bids over time:
> ![image](https://user-images.githubusercontent.com/25068506/69189263-0e7f3a00-0aec-11ea-9dc3-4ddeb4d174a3.png)

Mockup was shown to Piere-Marc, he expressed concerns about using a graph library that isn't finance-specific. 

We need to use a graph that has the following features:
-Overlapping volume
-Discontinuous x-axis (if displaying several days, hide hours where market is closed, end of one day should be stuck to start of next day on x-axis)
-Zooming
-Showing bid/ask price at the cursor's position on the graph

Will look into [React Stockcharts](http://rrag.github.io/react-stockcharts/documentation.html#/overview) for creating the graph.

**Comment by panoreak** [comment]
After looking into React Stockcharts we realized that we might need to create a Date wrapper. The library uses Date objects as the values for the X-axis. However, Date objects do not have nanosecond precision; we would add this precision with a wrapper class.

**Comment by panoreak** [comment]
Comment from meeting with Pierre-Marc:
- Add x-axis labels
