### ISSUE TITLE
Add menu option for selecting an instrument

### ISSUE THREAD

**Issue by chris-baur** [Lercerss/graphelier#114]
#77

There must be a component for the user to be able to choose/select between different instruments.

# Tasks
- [x] Add a drop down select to choose from available instruments
- [x] Add service call for getting instruments
- [x] Modify services to include use of specified instruments
