### ISSUE TITLE
Create Order Information Component

### ISSUE THREAD

**Issue by riyaGit** [Lercerss/graphelier#126]
Create a " swipeable temporary drawer" component that shows in addition information for the order when an order is clicked in the order book. 

# Tasks
- [x] Create Mockup
- [x] Create react component that will contain order information
        The component will be a drawer component containing a table
- [x] Get data from the backend containing the additional order information
- [x] Change the colour of the order "box" when it is clicked on

Story: [#110 ]

**Comment by riyaGit** [comment]
Mockup
<img width="1187" alt="Screen Shot 2020-01-16 at 2 42 22 PM" src="https://user-images.githubusercontent.com/26652806/72557464-ce7bcf80-386e-11ea-97b5-30462526566e.png">

**Comment by Lercerss** [comment]
Seeing this mockup, it might be better if the order information was a more temporary component such as a swipeable drawer.

**Comment by riyaGit** [comment]
I agree! This new mockup displays as such
<img width="1243" alt="Screen Shot 2020-01-16 at 3 05 13 PM" src="https://user-images.githubusercontent.com/26652806/72558946-b48fbc00-3871-11ea-8709-1503662c2af5.png">

**Comment by chimano** [comment]
Just to clarify, orders are created, modified, executed, and cancelled on the same day. So we should be showing the datetime and not just the date.
Also to clarify, will the message list contain all messages that have modified the order and the ones that will modify it in the future or will it only contain all the messages that have modified it up until the requested timestamp?

**Comment by Lercerss** [comment]
I believe it would be better to display all messages that affect the order, not just the ones that have been applied up until the requested timestamp. Maybe we could style the future messages differently for clarity?

**Comment by riyaGit** [comment]
Resolved in PR #187
