### ISSUE TITLE
Address Iteration 5 comments

### ISSUE THREAD

**Issue by Lercerss** [Lercerss/graphelier#134]
Based on feedback from last Iteration, we should improve a few things according to the grading scheme. 

| Metric       | Value           |
|--------------|-----------------|
| Story Points | 3 |
| Priority     | High |
| Risk         | Low |

# Tasks
- [X] Stories should link to their respective tasks and vice versa. We currently only have traceability from tasks to stories
- [x] Add class diagram for the scripts
- [x] Improve existing architecture diagram and make it more rigorous
- [x] Place all mockups in the wiki
- [x] Increase logging to be more verbose and use different log levels
- [x] Add comments to service/scripts tests, alternatively use BDD testing for all components
- [x] Review variable naming to be more descriptive
- [x] Test coverage and linting reports on builds

[//]: # (Make sure to add the appropriate feature label to your issue)

**Comment by Lercerss** [comment]
![scripts_class_diagram](https://user-images.githubusercontent.com/34099471/71497826-ea6bf280-2827-11ea-86de-303880e89aeb.jpg)
Class diagram representing the current state of the scripts

**Comment by Lercerss** [comment]
![data_view](https://user-images.githubusercontent.com/34099471/71857326-1ce1df00-30b5-11ea-8f99-646fe3786df1.jpg)
Data view representing the structure of the MongoDB collections
