### ISSUE TITLE
Release 3 Milestone Document

### ISSUE THREAD

**Issue by Lercerss** [Lercerss/graphelier#207]
As a developer, I want to document the work done on the application in the Milestone Document.
Additionally this release, we have to publish a video to replace the in-person demonstration of the Release 3 features. This video is only intended for the TA & Professor.

| Metric       | Value           |
|--------------|-----------------|
| Story Points | 5 |
| Priority     | High |
| Risk         | Low |

# Tasks
- Update relevant sections:
  - [x] Velocity & Iteration descritptions
  - [x] Architecture and Design
  - [x] Infrastructure
  - [x] Code files & descritptions
  - [x] Testing and CI
- Plan video
  - [x] 3 (?) features
  - [x] Demonstrate traceability from feature description to code to tests
  - [x] Cover "wow" feature
  - [x] Mention CI
- Record video
- Edit video
- If extra time, add badges for builds to README

**Comment by Lercerss** [comment]
Updated tasks to account for demo video
