### ISSUE TITLE
Refactor OrderBookSnapshot and date utils

### ISSUE THREAD

**Issue by alvyn279** [Lercerss/graphelier#234]
Refactor the app's `OrderBookSnapshot` component. The functionality depends too much on component states.

# Tasks
- [x] Migrate globals from component state variables to redux variables
- [x] Partition `render()` into multiple functions
- [x] Clean up `date-utils` functions
    - [x] Remove redundant functions
    - [x] Rename functions
- [x] Fix tests
- [ ] ~Improve testing coverage in date-utils~

Overall, also look for improvements on lifecycle management.
