### ISSUE TITLE
Integration for front end and its service calls

### ISSUE THREAD

**Issue by alvyn279** [Lercerss/graphelier#24]
Integrate all tasks done for front-end in Integration 2, along with changes made in the back-end.

# Tasks
- [x] Uniformize color scheme (make use of system colors) and layouts
- [x] Create axios interceptor
- [x] Adjust service calls to backend route (with correct url)
- [x] Display correct data based on these calls
