### ISSUE TITLE
Implement table component for displaying messages

### ISSUE THREAD

**Issue by alvyn279** [Lercerss/graphelier#31]
Besides the order book, we should see a scrollable table that displays all the message on its side.

Re-use MultiDirectionalScroll component for this

#50

# Tasks
- [ ] Load data (w/ new fetch)
- [ ] Implement paging (scroll hit up and scroll hit down)
- [ ] Implement onclick for a row (updates orderBook)
