### ISSUE TITLE
Add functionality for stepping forward and backwards at message level

### ISSUE THREAD

**Issue by alvyn279** [Lercerss/graphelier#52]
#28

When viewing the Orderbook, one should be able to step forward and backwards at message granularity.
Our request to the backend should take into consideration a timestamp along with an offset (in terms of messages).

When a message move is made:
- The orderbook should update up the price levels that have changed. It's **0 up to *offset_amount*** price levels that will need to be updated in the data structure used for the orderbook table. 

# Tasks
- [x] Add buttons to move forward and backwards at message-level
- [x] Send request for a particular timestamp and offset
- [x] Process response data and modify the values for listItems in OrderBookSnapshot

**Comment by alvyn279** [comment]
TODO: integrate once #35 BE functionality is implemented.

**Comment by alvyn279** [comment]
solved in #70
