### ISSUE TITLE
Display list of messages

### ISSUE THREAD

**Issue by alvyn279** [Lercerss/graphelier#54]
Alongside the orderbook, we should have a table that lists all the messages related to the orderbook, with a highlight on the message that represents the current orderbook state.

#50 

#Tasks
- [x] Mockup
- [x] Make request for messages:
    - [x] Orderbook should be infinitely scrollable on top and on bottom (paging)
- [x] Highlight correct message with respect to current orderbook state (change highlight when moving message)

**Comment by alvyn279** [comment]
Mockups will be needed for this.

**Comment by Lercerss** [comment]
On the backend side we have the following information on messages: time in ns, message type, order id, price, quantity, direction
Message type is an integer enum defined under https://github.com/Lercerss/graphelier/blob/master/core/scripts/models/message.py#L6

**Comment by Lercerss** [comment]
I think we should have the value for `direction` translated to buy/sell as the integer values are not very meaningful

**Comment by riyaGit** [comment]
Agreed. The mockup has been updated to reflect that.

**Comment by Lercerss** [comment]
> Agreed. The mockup has been updated to reflect that.

Thanks, looks good!

**Comment by chimano** [comment]
Will the orderbook and messages be seen at the same time or will the user have to scroll away from the orderbook to view the list of messages? It looks like if we fit both within the screen it'll hide too many rows from the orderbook. Is this what we want?
